### ISSUE TITLE
Missing Information - Android App - SDK Privacy Report.csv

### ISSUE THREAD

**Issue by 123dma** [Privado-Inc/SDK-Privacy-Report#14]
**ADmob SDK**
Platform: Android
Name (as on the CSV file): Android App - SDK Privacy Report.csv

On the official page https://developers.google.com/admob/android/play-data-disclosure of the admob documentation it is informed "The Google Mobile Ads SDK collects and shares the following data types automatically for advertising, analytics, and fraud prevention purposes ."

On the Google Play console form there is the option to select "collects or/and shares".

However in the spreadsheet "Android App - SDK Privacy Report.csv" there is only the answer for the option "Shared".

Could you explain better if it's a mistake or is it deliberate?

Thank´s

**Comment by vaibhavantil1** [comment]
@123dma - If you look at column two, it is Data Types Collected. We additionally give information if it is shared, Purposes, Required/Optional etc. So basically all the data types mentioned against a SDK are collected.

**Comment by vaibhavantil1** [comment]
@123dma - let me know if this solves the issue. Will close it accordingly.

**Comment by 123dma** [comment]
Hi @vaibhavantil1 , thank you. Yes, you can close the issue. If all data is to be checked as "Collected" the form on the Google Play console should be more intuitive.

**Comment by vaibhavantil1** [comment]
Yes. In fact we are reporting for only the data which is being collected by the SDK because then only it can be shared and have a purpose. Read this for more information by Google on definition of data collected:

Libraries and SDKs: This includes user data transmitted off device from your app by libraries and/or SDKs used in your app, irrespective of whether data is transmitted to you or a third party server.
